import {
  FontAwesome,
  Ionicons,
  MaterialCommunityIcons,
  MaterialIcons,
} from '../../../Assets/VectorIcons/Icons';

const dataTab = [
  {id: 1, title: 'Tìm kiếm', TypeIcon: FontAwesome, icon: 'search'},
  {id: 2, title: 'Trang chủ', TypeIcon: FontAwesome, icon: 'home'},
  {
    id: 3,
    title: 'Thông báo',
    TypeIcon: Ionicons,
    icon: 'md-notifications-sharp',
  },
  {id: 4, title: 'Cá nhân', TypeIcon: FontAwesome, icon: 'user'},
  {
    id: 5,
    title: 'Quet QR',
    TypeIcon: MaterialCommunityIcons,
    icon: 'qrcode-scan',
  },
  {id: 6, title: 'Cá nhân', TypeIcon: MaterialIcons, icon: 'monetization-on'},
  {id: 7, title: 'Cá nhân', TypeIcon: FontAwesome, icon: 'user'},
];
const dataCharacters = [
  'Monkey D. Luffy',
  'Roronoa Zoro',
  'Nami',
  'Usopp',
  'Sanji',
  'Tony Tony Chopper',
  'Nico Robin',
  'Franky',
  'Brook',
  'Jinbe',
  'Donquixote Mjosgard',
  'Sakazuki',
  'Kizaru',
  'Fujitora',
  'Ryokugyu',
  'Smoker',
  'Monkey D. Garp',
  'Monkey D. Luffy',
  'Roronoa Zoro',
  'Nami',
  'Usopp',
  'Sanji',
  'Tony Tony Chopper',
  'Nico Robin',
  'Franky',
  'Brook',
  'Jinbe',
  'Donquixote Mjosgard',
  'Sakazuki',
  'Kizaru',
  'Fujitora',
  'Ryokugyu',
  'Smoker',
  'Monkey D. Garp',
  'Monkey D. Luffy',
  'Roronoa Zoro',
  'Nami',
  'Usopp',
  'Sanji',
  'Tony Tony Chopper',
  'Nico Robin',
  'Franky',
  'Brook',
  'Jinbe',
  'Donquixote Mjosgard',
  'Sakazuki',
  'Kizaru',
  'Fujitora',
  'Ryokugyu',
  'Smoker',
  'Monkey D. Garp',
  'Monkey D. Luffy',
  'Roronoa Zoro',
  'Nami',
  'Usopp',
  'Sanji',
  'Tony Tony Chopper',
  'Nico Robin',
  'Franky',
  'Brook',
  'Jinbe',
  'Donquixote Mjosgard',
  'Sakazuki',
  'Kizaru',
  'Fujitora',
  'Ryokugyu',
  'Smoker',
  'Monkey D. Garp',
  'Monkey D. Luffy',
  'Roronoa Zoro',
  'Nami',
  'Usopp',
  'Sanji',
  'Tony Tony Chopper',
  'Nico Robin',
  'Franky',
  'Brook',
  'Jinbe',
  'Donquixote Mjosgard',
  'Sakazuki',
  'Kizaru',
  'Fujitora',
  'Ryokugyu',
  'Smoker',
  'Monkey D. Garp',
  'Monkey D. Luffy',
  'Roronoa Zoro',
  'Nami',
  'Usopp',
  'Sanji',
  'Tony Tony Chopper',
  'Nico Robin',
  'Franky',
  'Brook',
  'Jinbe',
  'Donquixote Mjosgard',
  'Sakazuki',
  'Kizaru',
  'Fujitora',
  'Ryokugyu',
  'Smoker',
  'Monkey D. Garp',
];
export {dataTab,dataCharacters};
